### ISSUE TITLE
free(full_path) in search_cmd_in_path.c function

### ISSUE THREAD

**Issue by Zaineb-Hammouda** [Zaineb-Hammouda/simple_shell#19]
i noticed that we haven't freed the full_path variable at the end of search_cmd_in_path.c function.

**Comment by Zaineb-Hammouda** [comment]
we can't free it anywhere else and we have to haha or else we get a mem leak. so i believe we can free it at the end of the search_cmd_in_path function

**Comment by Zaineb-Hammouda** [comment]
i can try freeing it if u don't mind and i'll check with valgrind again to see if it's fixed

**Comment by DuncanMoyo** [comment]
sorted by you i believe
