### ISSUE TITLE
memory leakage

### ISSUE THREAD

**Issue by Zaineb-Hammouda** [Zaineb-Hammouda/simple_shell#20]
after performing valgrind ./hsh and exiting our shell we lose 240 bytes each time. we should check what we need to free.

HEAP SUMMARY:
==647==     in use at exit: 240 bytes in 2 blocks
==647==   total heap usage: 8 allocs, 6 frees, 5,161 bytes allocated
==647==
==647== LEAK SUMMARY:
==647==    definitely lost: 120 bytes in 1 blocks
==647==    indirectly lost: 0 bytes in 0 blocks
==647==      possibly lost: 0 bytes in 0 blocks
==647==    still reachable: 120 bytes in 1 blocks
==647==         suppressed: 0 bytes in 0 blocks

**Comment by DuncanMoyo** [comment]
I've never successfully run valgrind on my system. I have tried installing it a few times...Will try again this time

**Comment by Zaineb-Hammouda** [comment]
u can use "sudo apt install valgrind". i think that's how i installed it. it does take about 130 megabytes of space i believe so maybe u have a space issue

**Comment by DuncanMoyo** [comment]
sorted by you
