### ISSUE TITLE
handle the “end of file” condition (Ctrl+D)

### ISSUE THREAD

**Issue by DuncanMoyo** [Zaineb-Hammouda/Simple_Shell#4]
We have to handle the “end of file” condition (Ctrl+D).

**Comment by DuncanMoyo** [comment]
What is the (Ctrl+D) supposed to do? My understanding was that when we type it in while the program us waiting for a command to be entered, the program will exit. I think that is currently being handled in our get_command function.

**Comment by Zaineb-Hammouda** [comment]
yes ctrl +D is same as EOF and we currently handle that issue. we however need to handle the exit command. which i think can be as easy as : 
if (strcmp(args[0], "exit") == 0)
{ 
exit (0); 
}

**Comment by DuncanMoyo** [comment]
Yes, that's task4. We will handle it then
